import dotenv from "dotenv";

dotenv.config();

const { 
	DISCORD_TOKEN, 
	DISCORD_CLIENT_ID, 
	MONGODB_CONNECT, 
	STRAVA_CLIENT_ID, 
	STRAVA_CLIENT_SECRET,
	STRAVA_REDIRECT_URI
} = process.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID || !MONGODB_CONNECT || !STRAVA_CLIENT_ID || !STRAVA_CLIENT_SECRET || !STRAVA_REDIRECT_URI) {
  throw new Error("Missing environment variables");
}

export const config = {
	DISCORD_TOKEN, 
	DISCORD_CLIENT_ID, 
	MONGODB_CONNECT, 
	STRAVA_CLIENT_ID, 
	STRAVA_CLIENT_SECRET,
	STRAVA_REDIRECT_URI
};